let
    source = TableDTR,
    renameHS = Table.TransformColumnTypes(Table.RenameColumns(source,{"hs", "HS Number"}),{"HS Number", type text}),
    renameRateType = Table.TransformColumnTypes(Table.RenameColumns(renameHS,{"country_group", "Rate type"}),{"Rate type", type text}),
    renamePercentage = Table.TransformColumnTypes(Table.RenameColumns(renameRateType,{"percentage", "Base rate %"}),{"Base rate %", Double.Type}),
    renameRatePerUOM = Table.TransformColumnTypes(Table.RenameColumns(renamePercentage,{"ratePerUOM", "Rate amount"}),{"Rate amount", Double.Type}),
    renameMultiplier = Table.TransformColumnTypes(Table.RenameColumns(renameRatePerUOM,{"multiplier", "Rate qty"}),{"Rate qty", Double.Type}),
    renameRateUOM = Table.TransformColumnTypes(Table.RenameColumns(renameMultiplier,{"rateUOM", "Rate qty uom"}),{"Rate qty uom", type text}),
    configYear = Excel.CurrentWorkbook(){[Name="Year"]}[Content]{0}[Column1],
    mainCG = Excel.CurrentWorkbook(){[Name="MainCG"]}[Content]{0}[Column1],
    addRow = Table.InsertRows(renameRateUOM, 0, {
        [version_date = Date.FromText(Number.ToText(configYear) & "0101"), #"HS Number" = "--", #"Rate type" = mainCG, #"Base rate %" = 0, #"Rate amount" = 0, #"Rate qty" = null, #"Rate qty uom" = ""],
        [version_date = Date.FromText(Number.ToText(configYear) & "0101"), #"HS Number" = "0000000000", #"Rate type" = mainCG, #"Base rate %" = 0, #"Rate amount" = 0, #"Rate qty" = null, #"Rate qty uom" = ""]}),
    dateZD14 = Date.From(Excel.CurrentWorkbook(){[Name="ZD14Date"]}[Content]{0}[Column1]),
    filterDate = Table.SelectRows(addRow, each [version_date] >= dateZD14),
    selectCols = Table.SelectColumns(filterDate,{"HS Number", "Rate type", "Base rate %", "Rate amount", "Rate qty", "Rate qty uom"}),
    addIndex = Table.AddIndexColumn(selectCols, "Index", 0, 1, Int64.Type),
    joinNOM = Table.NestedJoin(addIndex, {"HS Number"}, TableNOM, {"hs"}, "TableNOM", JoinKind.LeftOuter),
    expandNOM = Table.ExpandTableColumn(joinNOM, "TableNOM", {"alternate_unit_1", "full_description"}, {"Unit of measure", "Desc 1"}),
    sortIndex = Table.Sort(expandNOM,{{"Index", Order.Ascending}}),
    removeIndex = Table.RemoveColumns(sortIndex, "Index"),
    country = Excel.CurrentWorkbook(){[Name="Country"]}[Content]{0}[Column1],
    addCountry = Table.AddColumn(removeIndex, "Country", each country, type text),
    addDateFrom = Table.AddColumn(addCountry, "Date from", each Number.ToText(configYear) & "0101", type text),
    addDateTo = Table.AddColumn(addDateFrom, "Date to", each "99991231", type text),
    addLang1 = Table.AddColumn(addDateTo, "Lang 1", each "EN", type text),
    addDesc2 = Table.AddColumn(addLang1, "Desc 2", each "", type text),
    addDesc3 = Table.AddColumn(addDesc2, "Desc 3", each "", type text),
    addDesc4 = Table.AddColumn(addDesc3, "Desc 4", each "", type text),
    addDesc5 = Table.AddColumn(addDesc4, "Desc 5", each "", type text),
    addDesc6 = Table.AddColumn(addDesc5, "Desc 6", each "", type text),
    addDesc7 = Table.AddColumn(addDesc6, "Desc 7", each "", type text),
    addLang2 = Table.AddColumn(addDesc7, "Lang 2", each "ES", type text),
    addDesc21 = Table.DuplicateColumn(addLang2, "Desc 1", "Desc 21"),
    addDesc22 = Table.DuplicateColumn(addDesc21, "Desc 2", "Desc 22"),
    addDesc23 = Table.DuplicateColumn(addDesc22, "Desc 3", "Desc 23"),
    addDesc24 = Table.DuplicateColumn(addDesc23, "Desc 4", "Desc 24"),
    addDesc25 = Table.DuplicateColumn(addDesc24, "Desc 5", "Desc 25"),
    addDesc26 = Table.DuplicateColumn(addDesc25, "Desc 6", "Desc 26"),
    addDesc27 = Table.DuplicateColumn(addDesc26, "Desc 7", "Desc 27"),
    addRestCode = Table.AddColumn(addDesc27, "Restriction code", each "", type text),
    addchamp24 = Table.DuplicateColumn(addRestCode, "Date from", "Champ24"),
    addchamp25 = Table.DuplicateColumn(addchamp24, "Date to", "Champ25"),
    addRateCurr = Table.AddColumn(addchamp25, "Rate curr", each "", type text),
    addSpeccApp = Table.AddColumn(addRateCurr, "Spec App", each "", type text),
    addCertOri = Table.AddColumn(addSpeccApp, "Cert Ori", each "", type text),
    addCtyGrp = Table.AddColumn(addCertOri, "Cty Grp", each "", type text),
    reorderCols = Table.ReorderColumns(addCtyGrp,{"Country", "HS Number", "Date from", "Date to", "Lang 1", "Desc 1", "Desc 2", "Desc 3", "Desc 4", "Desc 5", "Desc 6", "Desc 7", "Lang 2", "Desc 21", "Desc 22", "Desc 23", "Desc 24", "Desc 25", "Desc 26", "Desc 27", "Unit of measure", "Restriction code", "Rate type", "Champ24", "Champ25", "Base rate %", "Rate amount", "Rate curr", "Rate qty", "Rate qty uom", "Spec App", "Cert Ori", "Cty Grp"})
in
    reorderCols