let
    source = TableDTR,
    mainCG = Excel.CurrentWorkbook(){[Name="caMainCG"]}[Content]{0}[Column1],
    filterID = Table.SelectRows(source, each [country_group] = mainCG),
    renameHS = Table.TransformColumnTypes(Table.RenameColumns(filterID,{"hs", "Can HS No."}),{"Can HS No.", type text}),
    renamePercentage = Table.TransformColumnTypes(Table.RenameColumns(renameHS,{"percentage", "MFN %"}),{"MFN %", Double.Type}),
    fillMultiplier = Table.ReplaceValue(renamePercentage, null, 1, Replacer.ReplaceValue, {"multiplier"}),
    mfnAmount = Table.AddColumn(fillMultiplier, "MFN $", each [ratePerUOM]/[multiplier]),
    renameRateUOM = Table.TransformColumnTypes(Table.RenameColumns(mfnAmount,{"rateUOM", "UOM $"}),{"UOM $", type text}),
    selectCols = Table.SelectColumns(renameRateUOM,{"Can HS No.", "MFN %", "MFN $", "UOM $"}),
    addRow = Table.InsertRows(selectCols, 0, {
        [#"Can HS No." = "--", #"MFN %" = 0, #"MFN $" = 0, #"UOM $" = ""],
        [#"Can HS No." = "0000000000", #"MFN %" = 0, #"MFN $" = 0, #"UOM $" = ""]}),
    addIndex = Table.AddIndexColumn(addRow, "Index", 0, 1, Int64.Type),
    joinNOM = Table.NestedJoin(addIndex, {"Can HS No."}, TableNOM, {"hs"}, "TableNOM", JoinKind.LeftOuter),
    expandNOM = Table.ExpandTableColumn(joinNOM, "TableNOM", {"alternate_unit_1"}, {"STAT UOM"}),
    sortIndex = Table.Sort(expandNOM,{{"Index", Order.Ascending}}),
    removeIndex = Table.RemoveColumns(sortIndex, "Index"),
    addClient = Table.AddColumn(removeIndex, "Cl.", each 10, Int64.Type),
    configYear = Excel.CurrentWorkbook(){[Name="Year"]}[Content]{0}[Column1],
    addYear = Table.AddColumn(addClient, "Year", each configYear, Int64.Type),
    addGPT = Table.AddColumn(Table.AddColumn(addYear, "GPT %", each 0, Int64.Type), "GPT $", each 0, Int64.Type),
    addUST = Table.AddColumn(Table.AddColumn(addGPT, "UST %", each 0, Int64.Type), "UST $", each 0, Int64.Type),
    addMX = Table.AddColumn(Table.AddColumn(addUST, "MEX %", each 0, Int64.Type), "MEX $", each 0, Int64.Type),
    addOther1 = Table.AddColumn(Table.AddColumn(addMX, "OTH %", each 0, Int64.Type), "OTH $", each 0, Int64.Type),
    addOther2 = Table.AddColumn(Table.AddColumn(addOther1, "OTH2 %", each 0, Int64.Type), "OTH2 $", each 0, Int64.Type),
    addOther3 = Table.AddColumn(Table.AddColumn(addOther2, "OTH3 %", each 0, Int64.Type), "OTH3 $", each 0, Int64.Type),
    add2450 = Table.AddColumn(Table.AddColumn(addOther3, "2450 %", each 0, Int64.Type), "2450 $", each 0, Int64.Type),
    add2460 = Table.AddColumn(Table.AddColumn(add2450, "2460 %", each 0, Int64.Type), "2460 $", each 0, Int64.Type),
    add2475 = Table.AddColumn(Table.AddColumn(add2460, "2475 %", each 0, Int64.Type), "2475 $", each 0, Int64.Type),
    addFREE = Table.AddColumn(Table.AddColumn(add2475, "FREE %", each 0, Int64.Type), "FREE $", each 0, Int64.Type),
    addCIAT = Table.AddColumn(Table.AddColumn(addFREE, "OTH4 %", each 0, Int64.Type), "OTH4 $", each 0, Int64.Type),
    addLDCT = Table.AddColumn(Table.AddColumn(addCIAT, "OTH5 %", each 0, Int64.Type), "OTH5 $", each 0, Int64.Type),
    addCCCT = Table.AddColumn(Table.AddColumn(addLDCT, "OTH6 %", each 0, Int64.Type), "OTH6 $", each 0, Int64.Type),
    addAUT = Table.AddColumn(Table.AddColumn(addCCCT, "OTH7 %", each 0, Int64.Type), "OTH7 $", each 0, Int64.Type),
    addNZT = Table.AddColumn(Table.AddColumn(addAUT, "OTH8 %", each 0, Int64.Type), "OTH8 $", each 0, Int64.Type),
    addPercentageUOM = Table.AddColumn(addNZT, "UOM %", each "", type text),
    addStatsUOM1 = Table.AddColumn(addPercentageUOM, "STAT1 UOM", each "", type text),
    addStatsQty1 = Table.AddColumn(addStatsUOM1, "STAT1 QTY", each 0, Int64.Type),
    addStatsUOM2 = Table.AddColumn(addStatsQty1, "STAT2 UOM", each "", type text),
    addStatsQty2 = Table.AddColumn(addStatsUOM2, "STAT2 QTY", each 0, Int64.Type),
    addMXUS = Table.AddColumn(Table.AddColumn(addStatsQty2, "Mex-US %", each 0, Int64.Type), "Mex-US $", each 0, Int64.Type),
    addRestriction = Table.AddColumn(addMXUS, "Rest Cd", each "", type text),
    addValidFrom = Table.AddColumn(addRestriction, "Date from", each Number.ToText(configYear) & "0101", type text),
    addValidTo = Table.AddColumn(addValidFrom, "Date to", each "99991231", type text),
    reorderCols = Table.ReorderColumns(addValidTo,{"Cl.", "Year", "Can HS No.", "MFN %", "MFN $", "GPT %", "GPT $", "UST %", "UST $", "MEX %", "MEX $", "OTH %", "OTH $", "OTH2 %", "OTH2 $", "OTH3 %", "OTH3 $", "2450 %", "2450 $", "2460 %", "2460 $", "2475 %", "2475 $", "FREE %", "FREE $", "OTH4 %", "OTH4 $", "OTH5 %", "OTH5 $", "OTH6 %", "OTH6 $", "OTH7 %", "OTH7 $", "OTH8 %", "OTH8 $", "UOM %", "UOM $", "STAT UOM", "STAT1 UOM", "STAT1 QTY", "STAT2 UOM", "STAT2 QTY", "Mex-US %", "Mex-US $", "Rest Cd", "Date from", "Date to"})
in
    reorderCols